subjects = {
    'Экономика': 'economy',
    'Английский гр. 1': 'english_grop_1',
    'Английский гр. 2': 'english_grop_2',
    'Биология': 'biology',
    'Математика': 'math',
    'Физика': 'physics',
    'География': 'geography',
    'ОБЖ': 'o_bj',
    'Химия': 'chemistry',
    'История': 'history',
    'Русский': 'russian',
    'Обществознание': 'social',
    'Физкультура': '_PE',
    'Информатика': 'inf',
}